### PR TITLE
Dev taryn2023

### LINKED ISSUE #3: New level at beginning of challenge
Adding a level at the very beginning of the challenge that has only qualitative and quantitative as choices (without discrete, continuous, nominal, ordinal).  That way, students get more practice before having to distinguish between the 4 choices

### LINKED ISSUE #4: Maybe add Prerequisite page
To help make the app more intuitive, maybe add a prerequisite tab that contains the necessary information.

### PR DESCRIPTION
**Pull request by tarynmch**

### CODE REVIEW

**Review by luqije — CHANGES_REQUESTED** [review]
Overview page:
don't forget to add yourself in the Acknowledgments.
Game page:
 - in level two, the spelling of QUestion 4 needs to change to Question. 
 - in level two, I would suggest putting question 3 and question 4 answer boxes under the questions to keep the consistency with Q1 and Q2. 
 - in level four, I have received I used all the tries, maybe add a description to explain how many tries the users have.   

Those are all my suggestions, great work!

**Comment by aisiricherrimane** [comment]
Everything seems correct. 
Just a suggestion on the prerequisites page:
maybe reduce the size of the flow chart under Explanatory, Response, and Confounding Variables
The prerequisites page is very well layed out Great work!!!!!!

**Review by luqije — DISMISSED** [review]
Great work! Just one small suggestion, maybe change the screenshot with level two, so it contains questions with plots, it may look bit more interesting than just wordings. Also, add the top (info button, survey, home button), so it shows the color of the app.

**Comment by neilhatfield** [comment]
Changes from https://github.com/EducationShinyAppTeam/Variable_Types_Matching_Game/pull/5/commits/be0dae9c660674b81ce8f7bcd44365bc62d49c79 will
Resolve #4
Close #3

**Pull request merged**
